#!/usr/bin/env bash

cd "$(dirname "$0")/.."

# Set up homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap caskroom/cask

# Command line
brew install git
ln -s .zshrc ~/.
brew install zsh
brew install task
brew install thefuck

# Basic
brew cask install google-chrome
brew cask install alfred
brew cask install spectacle
brew cask install keepingyouawake
brew cask install dropbox

# Communication
brew cask install franz
brew cask install viber

# Development
brew cask install iterm2
brew cask install sequel-pro
brew cask install sublime-text
brew cask install pophub

# Utilities
brew cask install istat-menus
brew cask install numi
brew cask install spotify
