#!/usr/bin/env bash

cd "$(dirname "$0")/.."

# Set up homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap caskroom/cask

# Command line
brew install git
brew install zsh
brew install task
brew install ag
brew install httpie

# Basic
brew cask install google-chrome
brew cask install alfred
brew cask install spectacle
brew cask install keepingyouawake
brew cask install dropbox

# Communication
brew cask install franz

# Development
brew cask install iterm2
brew cask install sequel-pro
brew cask install sublime-text
brew cask install pophub
brew cask install visual-studio-code
brew cask install docker
brew cask install postico

# Utilities
brew cask install istat-menus
brew cask install numi
brew cask install spotify

# pip
curl https://bootstrap.pypa.io/get-pip.py | sudo python

# Setup ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
ln -s .zshrc ~/.
sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
